---
title: "BoletinTema1jogarmo9"
author: "Jose Garcia Mora"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(robustbase)
A <- MASS::mammals
B <- robustbase::Animals2

dim(A)
head(A)
tail(A)
str(A)

rownames(A)
colnames(A)

dim(B)
head(B)
tail(B)
str(B)

rownames(B)
colnames(B)

commonAnimals <- intersect(rownames(A), rownames(B))
setdiff(rownames(A), rownames(B))
setdiff(rownames(B), rownames(A))
#Gran parte de los elementos aparecen diferentes porque no están bien escritos.
```

```{r}
library(MASS)
library(robustbase)
library(car)

qqPlot(log(mammals$brain))
qqPlot(log(Animals2$brain))
#Presentan un comportamineto similar, ya que sus graficas son similares.
```

```{r}
libReturn<-library()
libReturn[[2]][1:5,1]

head(libReturn$results,n=5)
sum(table(head(libReturn$results,n=5)))
#Hay 15 librerias instaladas.
```

```{r}
dim(cabbages)
str(cabbages)
head(cabbages)
tail(cabbages)
sum(is.na(cabbages))

dim(Chile)
str(Chile)
head(Chile)
tail(Chile)
sum(is.na(Chile))

summary(c(cabbages, Chile))
```

```{r}
library(ggplot2)
#qqplot(cabbages$VitC, y = )
#qqplot(cabbages$HeadWt, y=)
```

```{r}
ggplot(data=cabbages, aes(x=VitC, fill=Cult))+geom_histogram(alpha=0.5)
```

```{r}
#Diagrama de dispersión global.
plot(whiteside$Temp, whiteside$Gas)
#Diagrama de dispersión etiquetando según un factor.
plot(whiteside$Temp, whiteside$Gas, pch=c(6,16)[whiteside$Insul])
legend(x="topright",legend=c("Insul = Before","Insul = After"), pch=c(6,16))
# Planteamos 2 modelos lineales, uno para los datos de cada factor
Model1 <- lm(Gas ~ Temp, data = whiteside, subset = which(Insul == "Before"))
Model2 <- lm(Gas ~ Temp, data = whiteside, subset = which(Insul == "After"))
# Representamos las rectas correspondientes a cada modelo lineal
abline(Model1, lty=2)
abline(Model2)
```

```{r}
#Diagrama de dispersión global.
plot(cabbages$VitC, cabbages$HeadWt)

#Diagrama de dispersión etiquetando según un factor.
plot(cabbages$VitC, cabbages$HeadWt, pch=c(6,16)[whiteside$Insul])
legend(x="topright",legend=c("Cult = c39","Cult = c52"), pch=c(6,16))

# Planteamos 2 modelos lineales, uno para los datos de cada factor
Model1 <- lm(HeadWt ~ VitC, data = cabbages, subset = which(Cult == "c39"))
Model2 <- lm(HeadWt ~ VitC, data = cabbages, subset = which(Cult == "c52"))
# Representamos las rectas correspondientes a cada modelo lineal
abline(Model1, lty=2)
abline(Model2)
```

